/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-05-05 20:00:12 UTC)
 * on 2015-05-11 at 22:24:50 UTC 
 * Modify at your own risk.
 */

package com.appspot.smart_wish_list.smartwishlist.model;

/**
 * Item data message.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the smartwishlist. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SmartWishListItemData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String asin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean available;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String currency;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String formattedPrice;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String imageUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lastUpdate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double price;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String productUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String region;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String signature;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean soldByAmazon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String thumbnailUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAsin() {
    return asin;
  }

  /**
   * @param asin asin or {@code null} for none
   */
  public SmartWishListItemData setAsin(java.lang.String asin) {
    this.asin = asin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAvailable() {
    return available;
  }

  /**
   * @param available available or {@code null} for none
   */
  public SmartWishListItemData setAvailable(java.lang.Boolean available) {
    this.available = available;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCurrency() {
    return currency;
  }

  /**
   * @param currency currency or {@code null} for none
   */
  public SmartWishListItemData setCurrency(java.lang.String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFormattedPrice() {
    return formattedPrice;
  }

  /**
   * @param formattedPrice formattedPrice or {@code null} for none
   */
  public SmartWishListItemData setFormattedPrice(java.lang.String formattedPrice) {
    this.formattedPrice = formattedPrice;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImageUrl() {
    return imageUrl;
  }

  /**
   * @param imageUrl imageUrl or {@code null} for none
   */
  public SmartWishListItemData setImageUrl(java.lang.String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLastUpdate() {
    return lastUpdate;
  }

  /**
   * @param lastUpdate lastUpdate or {@code null} for none
   */
  public SmartWishListItemData setLastUpdate(java.lang.Double lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * @param price price or {@code null} for none
   */
  public SmartWishListItemData setPrice(java.lang.Double price) {
    this.price = price;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProductUrl() {
    return productUrl;
  }

  /**
   * @param productUrl productUrl or {@code null} for none
   */
  public SmartWishListItemData setProductUrl(java.lang.String productUrl) {
    this.productUrl = productUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRegion() {
    return region;
  }

  /**
   * @param region region or {@code null} for none
   */
  public SmartWishListItemData setRegion(java.lang.String region) {
    this.region = region;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSignature() {
    return signature;
  }

  /**
   * @param signature signature or {@code null} for none
   */
  public SmartWishListItemData setSignature(java.lang.String signature) {
    this.signature = signature;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSoldByAmazon() {
    return soldByAmazon;
  }

  /**
   * @param soldByAmazon soldByAmazon or {@code null} for none
   */
  public SmartWishListItemData setSoldByAmazon(java.lang.Boolean soldByAmazon) {
    this.soldByAmazon = soldByAmazon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getThumbnailUrl() {
    return thumbnailUrl;
  }

  /**
   * @param thumbnailUrl thumbnailUrl or {@code null} for none
   */
  public SmartWishListItemData setThumbnailUrl(java.lang.String thumbnailUrl) {
    this.thumbnailUrl = thumbnailUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public SmartWishListItemData setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  @Override
  public SmartWishListItemData set(String fieldName, Object value) {
    return (SmartWishListItemData) super.set(fieldName, value);
  }

  @Override
  public SmartWishListItemData clone() {
    return (SmartWishListItemData) super.clone();
  }

}
