/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-05-22 at 21:33:08 UTC 
 * Modify at your own risk.
 */

package com.appspot.smart_wish_list.smartwishlist.model;

/**
 * Result of the check.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the smartwishlist. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SmartWishListCheckResult extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long alertType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean hasAccount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean valid;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAlertType() {
    return alertType;
  }

  /**
   * @param alertType alertType or {@code null} for none
   */
  public SmartWishListCheckResult setAlertType(java.lang.Long alertType) {
    this.alertType = alertType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getHasAccount() {
    return hasAccount;
  }

  /**
   * @param hasAccount hasAccount or {@code null} for none
   */
  public SmartWishListCheckResult setHasAccount(java.lang.Boolean hasAccount) {
    this.hasAccount = hasAccount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getValid() {
    return valid;
  }

  /**
   * @param valid valid or {@code null} for none
   */
  public SmartWishListCheckResult setValid(java.lang.Boolean valid) {
    this.valid = valid;
    return this;
  }

  @Override
  public SmartWishListCheckResult set(String fieldName, Object value) {
    return (SmartWishListCheckResult) super.set(fieldName, value);
  }

  @Override
  public SmartWishListCheckResult clone() {
    return (SmartWishListCheckResult) super.clone();
  }

}
