/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-06-03 at 19:46:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.smart_wish_list.smartwishlist.model;

/**
 * Model definition for SmartWishListLoginResult.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the smartwishlist. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SmartWishListLoginResult extends com.google.api.client.json.GenericJson {

  /**
   * Result of the check.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private SmartWishListCheckResult checkResult;

  /**
   * Client data message.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private SmartWishListClientData clientData;

  /**
   * Result of the check.
   * @return value or {@code null} for none
   */
  public SmartWishListCheckResult getCheckResult() {
    return checkResult;
  }

  /**
   * Result of the check.
   * @param checkResult checkResult or {@code null} for none
   */
  public SmartWishListLoginResult setCheckResult(SmartWishListCheckResult checkResult) {
    this.checkResult = checkResult;
    return this;
  }

  /**
   * Client data message.
   * @return value or {@code null} for none
   */
  public SmartWishListClientData getClientData() {
    return clientData;
  }

  /**
   * Client data message.
   * @param clientData clientData or {@code null} for none
   */
  public SmartWishListLoginResult setClientData(SmartWishListClientData clientData) {
    this.clientData = clientData;
    return this;
  }

  @Override
  public SmartWishListLoginResult set(String fieldName, Object value) {
    return (SmartWishListLoginResult) super.set(fieldName, value);
  }

  @Override
  public SmartWishListLoginResult clone() {
    return (SmartWishListLoginResult) super.clone();
  }

}
